{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "prom-rds-exporter.fullname" . }}
  labels:
    app: {{ template "prom-rds-exporter.name" . }}
    chart: {{ template "prom-rds-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["secrets","configmap"]
    resourceNames: ["{{ template "prom-rds-exporter.fullname" . }}"]
    verbs: ["get"]
{{- end }}
