apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prom-rds-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "prom-rds-exporter.name" . }}
    chart: {{ template "prom-rds-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yml: |
    {{ tpl .Values.config . | nindent 4 }}
