{{- if and (not .Values.aws.role) (not .Values.aws.secret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prom-rds-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "prom-rds-exporter.name" . }}
    chart: {{ template "prom-rds-exporter.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{ if .Values.aws.aws_access_key_id }}
  aws_access_key_id: {{ .Values.aws.aws_access_key_id | b64enc | quote }}
  {{ end }}
  {{ if .Values.aws.aws_secret_access_key }}
  aws_secret_access_key: {{ .Values.aws.aws_secret_access_key | b64enc | quote }}
  {{ end }}
{{- end }}
